using System.Collections.Generic;

/// <summary>
/// Responsible for constructing worm segment instances based on a generated pattern.
///
/// The factory retrieves pooled segment objects from WormSegmentPool,
/// activates them, and assembles them into a sequential list representing
/// the worm's physical body.
///
/// Responsibilities:
/// - Spawn segment instances according to the pattern generated by
///   WormPatternBuilder.
/// - Identify and output references to the head and tail segments.
/// - Activate pooled objects before gameplay use.
/// - Attach WormSegmentDamageReceiver components so segments can report
///   damage events to WormCombatController.
///
/// This separation keeps spawning logic independent from gameplay systems
/// such as movement, combat, and pooling implementation.
/// </summary>
public sealed class WormFactory
{
    private readonly WormSegmentPool _pool;

    public WormFactory(WormSegmentPool pool)
    {
        _pool = pool;
    }

    public List<WormSegment> CreateSegments(
        List<WormSegmentType> pattern,
        out WormSegment head,
        out WormSegment tail)
    {
        List<WormSegment> segments = new(pattern.Count);

        head = null;
        tail = null;

        for (int i = 0; i < pattern.Count; i++)
        {
            WormSegment seg = _pool.Get(pattern[i]);

            if (seg == null)
                continue;

            seg.Activate();

            if (seg.Type == WormSegmentType.Head)
                head = seg;

            if (seg.Type == WormSegmentType.Tail)
                tail = seg;

            segments.Add(seg);
        }

        return segments;
    }

    public void AttachDamageReceivers(
        List<WormSegment> segments,
        WormCombatController combat)
    {
        for (int i = 0; i < segments.Count; i++)
        {
            WormSegment seg = segments[i];

            var receiver = seg.GetComponent<WormSegmentDamageReceiver>();

            if (receiver == null)
                receiver = seg.gameObject.AddComponent<WormSegmentDamageReceiver>();

            receiver.Initialize(combat, seg);
        }
    }
}